## 引入模組

In [3]:
import requests
import pandas as pd
import datetime
import json

In [4]:
josn_url='https://quality.data.gov.tw/dq_download_json.php?nid=123026&md5_url=4d8de527a0bcd8a7b1aeae91120f021d'

## 資料網址  
https://data.gov.tw/dataset/123026  
檢視資料  
每五分鐘更新一次

In [224]:
csv_url='https://data.ntpc.gov.tw/api/datasets/71CD1490-A2DF-4198-BEF1-318479775E8A/csv/file'

In [225]:
df1=pd.read_csv(csv_url)
df1

,sno,sna,tot,sbi,sarea,mday,lat,lng,ar,sareaen,snaen,aren,bemp,act
0,1001,大鵬華城,38,9,新店區,20210219121441,24.991160,121.533980,新北市新店區中正路700巷3號,Xindian Dist.,Dapeng Community,"No. 3, Lane 700 Chung Cheng Road, Xindian Dist...",29,1
1,1002,汐止火車站,56,36,汐止區,20210219121429,25.068914,121.662748,南昌街/新昌路口(西側廣場),Xizhi Dist.,Xizhi Railway Station,Nanchang St./Xinchang Rd.,18,1
2,1003,汐止區公所,46,3,汐止區,20210219121440,25.064162,121.658301,新台五路一段/仁愛路口(新台五路側汐止地政事務所前機車停車場),Xizhi Dist.,Xizhi Dist. Office,"Sec. 1, Xintai 5th Rd./Ren’ai Rd.",43,1
3,1004,國泰綜合醫院,56,4,汐止區,20210219121430,25.073150,121.662555,建成路78號對面停車場,Xizhi Dist.,Cathay General Hospital,"No78, Jiancheng Rd",52,1
4,1005,裕隆公園,40,8,新店區,20210219121445,24.979649,121.546319,寶中路/品牌路口(東南側),Xindian Dist.,Yulon Park,Baozhong Rd./,32,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,1753,四維國凱街口(立天下社區),40,9,樹林區,20210219121421,24.979320,121.422410,四維路121號(旁),Shulin Dist.,Siwei & Guokai Intersection,"No. 121, Siwei Rd.",31,1
649,1757,中山環金路口,34,14,金山區,20210219121435,25.217940,121.641400,中山路/中興路口(公園綠地),Jinshan Dist.,Zhongshan & Huanjin Intersection,Zhongshan Rd. & Zhongxing Rd. Intersection,19,1
650,1760,龍米停車場,36,8,八里區,20210219121421,25.156780,121.436040,龍米路二段150號(旁),Bali Dist.,Longmi Parking Lot,"No. 150, Sec. 2, Longmi Rd.",27,1
651,1761,雙和醫院,30,6,中和區,20210219121416,24.993670,121.494110,中正路281號(公車亭旁),Zhonghe Dist.,Shuang Ho Hospital,"No. 281, Zhongzheng Rd.",24,1
652,1763,捷運三重站(1號出口),40,13,三重區,20210219121445,25.054640,121.483220,捷運路36號(旁),Sanchong Dist.,MRT Sanchong Station (Exit.1),"No. 36, Jieyun Rd. (Side)",27,1

## 分析資料

In [226]:
df1.head()

,sno,sna,tot,sbi,sarea,mday,lat,lng,ar,sareaen,snaen,aren,bemp,act
0,1001,大鵬華城,38,9,新店區,20210219121441,24.991160,121.533980,新北市新店區中正路700巷3號,Xindian Dist.,Dapeng Community,"No. 3, Lane 700 Chung Cheng Road, Xindian Dist...",29,1
1,1002,汐止火車站,56,36,汐止區,20210219121429,25.068914,121.662748,南昌街/新昌路口(西側廣場),Xizhi Dist.,Xizhi Railway Station,Nanchang St./Xinchang Rd.,18,1
2,1003,汐止區公所,46,3,汐止區,20210219121440,25.064162,121.658301,新台五路一段/仁愛路口(新台五路側汐止地政事務所前機車停車場),Xizhi Dist.,Xizhi Dist. Office,"Sec. 1, Xintai 5th Rd./Ren’ai Rd.",43,1
3,1004,國泰綜合醫院,56,4,汐止區,20210219121430,25.073150,121.662555,建成路78號對面停車場,Xizhi Dist.,Cathay General Hospital,"No78, Jiancheng Rd",52,1
4,1005,裕隆公園,40,8,新店區,20210219121445,24.979649,121.546319,寶中路/品牌路口(東南側),Xindian Dist.,Yulon Park,Baozhong Rd./,32,1

In [227]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sno      653 non-null    int64
 1   sna      653 non-null    object
 2   tot      653 non-null    int64
 3   sbi      653 non-null    int64
 4   sarea    653 non-null    object
 5   mday     653 non-null    int64
 6   lat      653 non-null    float64
 7   lng      653 non-null    float64
 8   ar       653 non-null    object
 9   sareaen  653 non-null    object
 10  snaen    652 non-null    object
 11  aren     650 non-null    object
 12  bemp     653 non-null    int64
 13  act      653 non-null    int64
dtypes: float64(2), int64(6), object(6)
memory usage: 71.5+ KB

In [228]:
df1.describe()

,sno,tot,sbi,mday,lat,lng,bemp,act
count,653.000000,653.000000,653.000000,6.530000e+02,653.000000,653.000000,653.000000,653.000000
mean,1348.154671,41.415008,12.493109,2.021012e+13,25.033866,121.472289,27.935681,0.990812
std,218.185677,12.779665,10.757307,9.378920e+08,0.059392,0.071694,12.422724,0.095488
min,1001.000000,16.000000,0.000000,2.020110e+13,24.907449,121.329380,0.000000,0.000000
25%,1164.000000,34.000000,5.000000,2.021022e+13,24.992020,121.433154,20.000000,1.000000
50%,1327.000000,38.000000,11.000000,2.021022e+13,25.023360,121.462890,27.000000,1.000000
75%,1496.000000,46.000000,17.000000,2.021022e+13,25.068940,121.497818,34.000000,1.000000
max,1763.000000,114.000000,90.000000,2.021022e+13,25.285491,121.827190,92.000000,1.000000

### 保留需要資料  
sno(站點代號)、sna(中文場站名稱)、tot(場站總停車格)、sbi(可借車位數)、sarea(中文場站區域)、mday(資料更新時間)、lat(緯度)、lng(經度)、ar(中文地址)、sareaen(英文場站區域)、snaen(英文場站名稱)、aren(英文地址)、bemp(可還空位數)、act(場站是否暫停營運)

#### columns=['日期','站點代號','站點','總車數','可借數','可還數','是否營運']

In [229]:
df2=df1[['mday','sno','sna','tot','sbi','bemp','act']]
df2

               mday   sno            sna  tot  sbi  bemp  act
0    20210219121441  1001           大鵬華城   38    9    29    1
1    20210219121429  1002          汐止火車站   56   36    18    1
2    20210219121440  1003          汐止區公所   46    3    43    1
3    20210219121430  1004         國泰綜合醫院   56    4    52    1
4    20210219121445  1005           裕隆公園   40    8    32    1
..              ...   ...            ...  ...  ...   ...  ...
648  20210219121421  1753  四維國凱街口(立天下社區)   40    9    31    1
649  20210219121435  1757         中山環金路口   34   14    19    1
650  20210219121421  1760          龍米停車場   36    8    27    1
651  20210219121416  1761           雙和醫院   30    6    24    1
652  20210219121445  1763    捷運三重站(1號出口)   40   13    27    1

[653 rows x 7 columns]

## 轉換日期

In [230]:
pd.to_datetime(df2['mday'])

0     1970-01-01 05:36:50.219121441
1     1970-01-01 05:36:50.219121429
2     1970-01-01 05:36:50.219121440
3     1970-01-01 05:36:50.219121430
4     1970-01-01 05:36:50.219121445
                   ...
648   1970-01-01 05:36:50.219121421
649   1970-01-01 05:36:50.219121435
650   1970-01-01 05:36:50.219121421
651   1970-01-01 05:36:50.219121416
652   1970-01-01 05:36:50.219121445
Name: mday, Length: 653, dtype: datetime64[ns]

## 撰寫轉換函示

In [231]:
def convert_date(date):
    date=str(date)
    year=date[:4]
    math=date[4:6]
    day=date[6:8]
    hh=date[8:10]
    mm=date[10:12]
    ss=date[12:14]
    
    return f'{year}/{math}/{day} {hh}:{mm}:{ss}'

In [232]:
convert_date('20210219105945')

'2021/02/19 10:59:45'

In [233]:
df2['mday'].apply(convert_date)

0      2021/02/19 12:14:41
1      2021/02/19 12:14:29
2      2021/02/19 12:14:40
3      2021/02/19 12:14:30
4      2021/02/19 12:14:45
              ...
648    2021/02/19 12:14:21
649    2021/02/19 12:14:35
650    2021/02/19 12:14:21
651    2021/02/19 12:14:16
652    2021/02/19 12:14:45
Name: mday, Length: 653, dtype: object

In [234]:
df2['mday']=df2['mday'].apply(convert_date)
df2.head()

<ipython-input-234-a4a4472cd395>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['mday']=df2['mday'].apply(convert_date)

                  mday   sno     sna  tot  sbi  bemp  act
0  2021/02/19 12:14:41  1001    大鵬華城   38    9    29    1
1  2021/02/19 12:14:29  1002   汐止火車站   56   36    18    1
2  2021/02/19 12:14:40  1003   汐止區公所   46    3    43    1
3  2021/02/19 12:14:30  1004  國泰綜合醫院   56    4    52    1
4  2021/02/19 12:14:45  1005    裕隆公園   40    8    32    1

In [235]:
df2

                    mday   sno            sna  tot  sbi  bemp  act
0    2021/02/19 12:14:41  1001           大鵬華城   38    9    29    1
1    2021/02/19 12:14:29  1002          汐止火車站   56   36    18    1
2    2021/02/19 12:14:40  1003          汐止區公所   46    3    43    1
3    2021/02/19 12:14:30  1004         國泰綜合醫院   56    4    52    1
4    2021/02/19 12:14:45  1005           裕隆公園   40    8    32    1
..                   ...   ...            ...  ...  ...   ...  ...
648  2021/02/19 12:14:21  1753  四維國凱街口(立天下社區)   40    9    31    1
649  2021/02/19 12:14:35  1757         中山環金路口   34   14    19    1
650  2021/02/19 12:14:21  1760          龍米停車場   36    8    27    1
651  2021/02/19 12:14:16  1761           雙和醫院   30    6    24    1
652  2021/02/19 12:14:45  1763    捷運三重站(1號出口)   40   13    27    1

[653 rows x 7 columns]

In [236]:
import sqlite3

In [237]:
datas=df2.values
datas

array([['2021/02/19 12:14:41', 1001, '大鵬華城', ..., 9, 29, 1],
       ['2021/02/19 12:14:29', 1002, '汐止火車站', ..., 36, 18, 1],
       ['2021/02/19 12:14:40', 1003, '汐止區公所', ..., 3, 43, 1],
       ...,
       ['2021/02/19 12:14:21', 1760, '龍米停車場', ..., 8, 27, 1],
       ['2021/02/19 12:14:16', 1761, '雙和醫院', ..., 6, 24, 1],
       ['2021/02/19 12:14:45', 1763, '捷運三重站(1號出口)', ..., 13, 27, 1]],
      dtype=object)

## 建立資料庫  
mydb  
CREATE TABLE "youbike_data" (
	"id"	INTEGER,
	"date"	TEXT,
	"sno"	BLOB,
	"sna"	TEXT,
	"tot"	INTEGER,
	"sbi"	INTEGER,
	"bemp"	INTEGER,
	"act"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
)

In [238]:
count=0

try:
    conn=sqlite3.connect('mydb.db')
    print('open db.')
    curosr=conn.cursor()    
   
    
        
    insert_str='insert into youbike_data(date,sno,sna,tot,sbi,bemp,act) values("{}","{}","{}",{},{},{},{});'
       
    
    for data in datas:
        #檢查是否有重複資料
        select_str=f'select date,sno from youbike_data where date="{data[0]}" and sno="{data[1]}"'
        
        if len(list(curosr.execute(select_str)))==0:        
            count+=1
            curosr.execute(insert_str.format(data[0],data[1],data[2],data[3],data[4],data[5],data[6]))
                       
    conn.commit()
    
    print('寫入資料庫成功!')
    print(f'更新{count}筆資料')
        
except Exception as e:
    print(e)
finally:
    conn.close()
    print('close db.')

open db.
寫入資料庫成功!
更新645筆資料
close db.

## pandas 讀取資料庫方式

In [245]:
with sqlite3.connect('mydb.db') as con:
    df3 = pd.read_sql_query("SELECT * FROM youbike_data", con=con)

In [248]:
df3.sort_values(by='tot',ascending=False).head(10)

        id                 date   sno           sna  tot  sbi  bemp  act
281    282  2021/02/19 11:28:40  1282  捷運頭前庄站(1號出口)  114   72    40    1
1582  1583  2021/02/19 12:14:40  1282  捷運頭前庄站(1號出口)  114   76    36    1
934    935  2021/02/19 11:28:40  1282  捷運頭前庄站(1號出口)  114   72    40    1
234    235  2021/02/19 11:28:21  1235         捷運淡水站  106   19    87    1
1535  1536  2021/02/19 12:14:22  1235         捷運淡水站  106   90    16    1
887    888  2021/02/19 11:28:21  1235         捷運淡水站  106   19    87    1
1412  1413  2021/02/19 12:14:16  1108   捷運板橋站(1號出口)  102   66    35    1
107    108  2021/02/19 11:28:28  1108   捷運板橋站(1號出口)  102   56    45    1
760    761  2021/02/19 11:28:28  1108   捷運板橋站(1號出口)  102   56    45    1
1264  1265  2021/02/19 11:28:39  1705        新店行政園區  100   48    51    1

## 如何定時抓取?

In [249]:
import sched
import time

## 需等待時間完成

In [250]:
import time
for i in range(5):    
    print(i)
    time.sleep(1)

0
1
2
3
4

## 使用scheduler套件  
可排程同時運行

In [253]:
import time
import sched
import datetime


#生成scheduler物件
s = sched.scheduler(time.time, time.sleep) 

def print_time(count):   
    print(count,datetime.datetime.now())


count=0
s.enter(1, 0, print_time, (count,)) 
count+=1
s.enter(3, 1, print_time, (count,))

s.run()

0 2021-02-19 12:25:06.855010
1 2021-02-19 12:25:08.866105

## 建立youbike爬蟲函式